version: "3"
services:
  back:
    build: ./back
  front-nginx:
    build:
      context: .
      dockerfile: front-nginx-Dockerfile
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-sites.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "back"
